// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signature.proto

package pbraven

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignatureAlgorithm int32

const (
	SignatureAlgorithm_SIG_NONE SignatureAlgorithm = 0
)

var SignatureAlgorithm_name = map[int32]string{
	0: "SIG_NONE",
}

var SignatureAlgorithm_value = map[string]int32{
	"SIG_NONE": 0,
}

func (x SignatureAlgorithm) String() string {
	return proto.EnumName(SignatureAlgorithm_name, int32(x))
}

func (SignatureAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76962cacebaec211, []int{0}
}

type Signature struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_76962cacebaec211, []int{0}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Signature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterEnum("pbraven.SignatureAlgorithm", SignatureAlgorithm_name, SignatureAlgorithm_value)
	proto.RegisterType((*Signature)(nil), "pbraven.Signature")
}

func init() { proto.RegisterFile("signature.proto", fileDescriptor_76962cacebaec211) }

var fileDescriptor_76962cacebaec211 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xce, 0x4c, 0xcf,
	0x4b, 0x2c, 0x29, 0x2d, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0x2a,
	0x4a, 0x2c, 0x4b, 0xcd, 0x53, 0xf2, 0xe0, 0xe2, 0x0c, 0x86, 0xc9, 0x09, 0xc9, 0x72, 0x71, 0x15,
	0x94, 0x26, 0xe5, 0x64, 0x26, 0xc7, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x71, 0x42, 0x44, 0xbc, 0x53, 0x2b, 0x85, 0x64, 0xb8, 0x38, 0xe1, 0xe6, 0x48, 0x30, 0x41, 0x64,
	0xe1, 0x02, 0x5a, 0x4a, 0x5c, 0x42, 0x70, 0x93, 0x1c, 0x73, 0xd2, 0xf3, 0x8b, 0x32, 0x4b, 0x32,
	0x72, 0x85, 0x78, 0xb8, 0x38, 0x82, 0x3d, 0xdd, 0xe3, 0xfd, 0xfc, 0xfd, 0x5c, 0x05, 0x18, 0x92,
	0xd8, 0xc0, 0xb6, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x26, 0x3b, 0x63, 0x90, 0x00,
	0x00, 0x00,
}
